spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cucaqi?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root

mybatis:
  type-aliases-package: com.cucaqi.entity

server:
  port: 8085

