spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cucaqi?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "20206880"

mybatis:
  type-aliases-package: com.cucaqi.entity
  mapper-locations: classpath*:/mapper/*.xml
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: deleted #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
 

server:
  port: 8085

